version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # Infelizmente o backend não se conecta com o db quando inicio tudo pelo docker compose,
  # quando inicio apenas o db e inicio o back na mão ele conecta normal
  # backend:
  #   build: ./backend
  #   container_name: fastapi_backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db

  # frontend:
  #   build: ./frontend
  #   container_name: frontend_server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - backend

volumes:
  mysql_data: